{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Исключения\n",
    "В этом лонгриде рассмотрим, что такое исключения, как их \"вызывать\" и \"обрабатывать\""
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Что такое?\n",
    "\n",
    "**Исключения** и их **обработка** в языках программирования - это механизм, позволяющий программе реагировать на нетипичные ситуации, не прекращая свою работу.\n",
    "\n",
    "### В Python\n",
    "\n",
    "Исключения в Python - это обычный тип данных.\n",
    "\n",
    "Основная их особенность - исключения могут **вызываться** и **обрабатываться**, а основная их цель - нести в себе информацию о нетипичной ситуации, с которой столкнулся интерпретатор при выполнении программ\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [
    {
     "ename": "ZeroDivisionError",
     "evalue": "division by zero",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[1;32mIn [1], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;66;03m# например, в случае деления числа на ноль\u001b[39;00m\n\u001b[1;32m----> 2\u001b[0m \u001b[38;5;241;43m100\u001b[39;49m\u001b[43m \u001b[49m\u001b[38;5;241;43m/\u001b[39;49m\u001b[43m \u001b[49m\u001b[38;5;241;43m0\u001b[39;49m\n",
      "\u001b[1;31mZeroDivisionError\u001b[0m: division by zero"
     ]
    }
   ],
   "source": [
    "# например, в случае деления числа на ноль\n",
    "100 / 0"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Вы видите тип исключения, строку, вызвавшую это исключение, а также само исключение.\n",
    "\n",
    "В Python присутствует большое число видов исключений:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "can only concatenate str (not \"int\") to str",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[1;32mIn [2], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;66;03m# например, если \"сложить\" объекты разных типов\u001b[39;00m\n\u001b[1;32m----> 2\u001b[0m \u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43m1\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m \u001b[49m\u001b[38;5;241;43m+\u001b[39;49m\u001b[43m \u001b[49m\u001b[38;5;241;43m2\u001b[39;49m\n",
      "\u001b[1;31mTypeError\u001b[0m: can only concatenate str (not \"int\") to str"
     ]
    }
   ],
   "source": [
    "# например, если \"сложить\" объекты разных типов\n",
    "'1' + 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [
    {
     "ename": "IndexError",
     "evalue": "list index out of range",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mIndexError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[1;32mIn [3], line 3\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;66;03m# или вызвать элемент по индексу, выходящему за пределы коллекции\u001b[39;00m\n\u001b[0;32m      2\u001b[0m l \u001b[38;5;241m=\u001b[39m [\u001b[38;5;241m1\u001b[39m,\u001b[38;5;241m2\u001b[39m,\u001b[38;5;241m3\u001b[39m]\n\u001b[1;32m----> 3\u001b[0m \u001b[43ml\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;241;43m5\u001b[39;49m\u001b[43m]\u001b[49m\n",
      "\u001b[1;31mIndexError\u001b[0m: list index out of range"
     ]
    }
   ],
   "source": [
    "# или вызвать элемент по индексу, выходящему за пределы коллекции\n",
    "l = [1,2,3]\n",
    "l[5]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Try-Except\n",
    "Это классическая конструкция обработки исключений применяется и в Python.\n",
    "\n",
    "В блоке `try` содержится код, в котором может произойти нетипичная ситуация. Блоки `except` позволяют обрабатывать каждую такую ситуацию по отдельности"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Ты пытаешься сложить нескладываемое\n"
     ]
    }
   ],
   "source": [
    "# попробуем записать с помощью неё пример с исключением выше\n",
    "# при вызове исключения интерпретатор сразу перейдёт в блок\n",
    "# с обработчиком соответствующего исключения\n",
    "try:\n",
    "    '1' + 2\n",
    "\n",
    "except TypeError:\n",
    "    print(\"Ты пытаешься сложить нескладываемое\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Такого индекса нет в коллекции\n"
     ]
    }
   ],
   "source": [
    "# обработчиков может быть несколько - для разных сценариев\n",
    "try:\n",
    "    l[5]\n",
    "\n",
    "except TypeError:\n",
    "    print(\"Ты пытаешься сложить нескладываемое\")\n",
    "\n",
    "except IndexError:\n",
    "    print(\"Такого индекса нет в коллекции\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Else и Finally\n",
    "Интерпретатор Python также выполнит блок кода, находящийся в `else`, если код выполнился без исключений, а также блок кода, находящийся в `finally` в любом случае.\n",
    "\n",
    "В блок `finally` имеет смысл помещать действия, которые обязательно должны быть выполнены (например, файл должен быть закрыт даже при возникновении ошибок)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Исключения не вызывались\n",
      "Я выполнюсь в любом случае\n"
     ]
    }
   ],
   "source": [
    "# обработчиков может быть несколько - для разных сценариев\n",
    "try:\n",
    "    l[0]\n",
    "\n",
    "except IndexError:\n",
    "    print(\"Такого индекса нет в коллекции\")\n",
    "\n",
    "else:\n",
    "    print(\"Исключения не вызывались\")\n",
    "\n",
    "finally:\n",
    "    print(\"Я выполнюсь в любом случае\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Откуда появляются исключения?\n",
    "Любое исключение может быть вызвано с помощью команды `raise`\n",
    "\n",
    "Например:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [
    {
     "ename": "IndexError",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mIndexError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[1;32mIn [7], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m \u001b[38;5;28;01mraise\u001b[39;00m(\u001b[38;5;167;01mIndexError\u001b[39;00m)\n",
      "\u001b[1;31mIndexError\u001b[0m: "
     ]
    }
   ],
   "source": [
    "raise(IndexError)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "При попытке деления на ноль, доступа к индексу, который не содержится в коллекции и т.д. соответствующие исключения вызывается с помощью той же команды `raise`, просто это уже реализовано создателями Python при описании этих функций."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Нужно ли обрабатывать все исключения?\n",
    "Если требуется обеспечить бесперебойную работу программы - то да\n",
    "\n",
    "Однако при обработке исключения мы нередко теряем ценную информацию о том, где и почему оно появилось.\n",
    "\n",
    "Если же вы хотите просто добавить какую-то информацию к исключению, обработайте его и там же в блоке except вызовите снова"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Вывожу ценную информацию и вызываю после этого исключение\n"
     ]
    },
    {
     "ename": "IndexError",
     "evalue": "list index out of range",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mIndexError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[1;32mIn [8], line 8\u001b[0m\n\u001b[0;32m      5\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mВывожу ценную информацию и вызываю после этого исключение\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m      6\u001b[0m \u001b[38;5;66;03m# можно вызвать любое исключение\u001b[39;00m\n\u001b[0;32m      7\u001b[0m \u001b[38;5;66;03m# но логично \"пробросить дальше\" то же самое, добавив своё сообщение\u001b[39;00m\n\u001b[1;32m----> 8\u001b[0m \u001b[38;5;28;01mraise\u001b[39;00m(e)\n",
      "Cell \u001b[1;32mIn [8], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m----> 2\u001b[0m     \u001b[43ml\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;241;43m5\u001b[39;49m\u001b[43m]\u001b[49m\n\u001b[0;32m      4\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mIndexError\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[0;32m      5\u001b[0m     \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mВывожу ценную информацию и вызываю после этого исключение\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "\u001b[1;31mIndexError\u001b[0m: list index out of range"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    l[5]\n",
    "\n",
    "except IndexError as e:\n",
    "    print(\"Вывожу ценную информацию и вызываю после этого исключение\")\n",
    "    # можно вызвать любое исключение\n",
    "    # но логично \"пробросить дальше\" то же самое, добавив своё сообщение\n",
    "    raise(e)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "pycharm": {
     "name": "#%% md\n"
    }
   },
   "source": [
    "### Если вы хотите обрабатывать любое исключение\n",
    "Пишите `except Exception:` вместо `except:`\n",
    "Второй вариант аналогичен `except BaseException`, что включает в себя даже исключение, которое вызывается, когда вы пытаетесь прервать ход выполнения программы с помощью клавиатуры. Во втором случае можете случайно попасть в бесконечный цикл, отключить который можно будет только через диспетчер задач"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Вывожу ценную информацию и вызываю после этого исключение. Сюда попадёт любое исключение, кроме прерывания программы с помощью 'Ctrl+X'\n"
     ]
    },
    {
     "ename": "ZeroDivisionError",
     "evalue": "division by zero",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[1;32mIn [9], line 6\u001b[0m\n\u001b[0;32m      4\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[0;32m      5\u001b[0m     \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mВывожу ценную информацию и вызываю после этого исключение. Сюда попадёт любое исключение, кроме прерывания программы с помощью \u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mCtrl+X\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m----> 6\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m(e)\n",
      "Cell \u001b[1;32mIn [9], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m----> 2\u001b[0m     \u001b[38;5;241;43m100\u001b[39;49m\u001b[38;5;241;43m/\u001b[39;49m\u001b[38;5;241;43m0\u001b[39;49m\n\u001b[0;32m      4\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[0;32m      5\u001b[0m     \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mВывожу ценную информацию и вызываю после этого исключение. Сюда попадёт любое исключение, кроме прерывания программы с помощью \u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mCtrl+X\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "\u001b[1;31mZeroDivisionError\u001b[0m: division by zero"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    100/0\n",
    "\n",
    "except Exception as e:\n",
    "    print(\"Вывожу ценную информацию и вызываю после этого исключение. Сюда попадёт любое исключение, кроме прерывания программы с помощью 'Ctrl+X'\")\n",
    "    raise(e)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Обработку исключений нужно добавлять в любую программу?\n",
    "### Нет\n",
    "\n",
    "- обработка исключений занимает вычислительные ресурсы, из-за чего необходимо лишнее время на выполнение программы\n",
    "- не все нетипичные ситуации можно заранее предусмотреть\n",
    "- конструкции `try`-`expect`-`else`-`finally` делают код менее читаемым для программиста\n",
    "\n",
    "Не обработанные пользователем исключения попадают метод sys.excepthook, который и выводит их в поток вывода в сообщении, которое вы видите при появлении исключения."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Собственные исключения\n",
    "Как было сказано выше, все исключения наследуются от класса Exception (а он - от BaseException).\n",
    "\n",
    "Создадим собственное исключение и вызовем его"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "('Oops!', 'Something went bad!')\n"
     ]
    }
   ],
   "source": [
    "class MyException(Exception):\n",
    "    def __init__(self, val1, val2):\n",
    "        # в этих полях будут обычные строки\n",
    "        # но логично хранить в них полезную информацию об ошибке\n",
    "        self.value1 = val1\n",
    "        self.value2 = val2\n",
    "\n",
    "try:\n",
    "    # вызовем MyException прямо в блоке try\n",
    "    raise MyException(\"Oops!\", \"Something went bad!\")\n",
    "\n",
    "except MyException as exc:\n",
    "    print(exc.args)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Нужно ли создавать собственные исключения?\n",
    "### Нет (в большинстве случаев)\n",
    "\n",
    "Лучше изучить уже существующие: благо, число видов уже реализованных создателями Python исключений велико.\n",
    "\n",
    "Создавать собственные исключения имеет смысл при написании собственной библиотеки расширений, создании объектов со сложной внутренней логикой, или выполнении сложных задач, в которых необходимо документировать сложные \"нетипичные\" ситуации.\n",
    "\n",
    "Хотя даже в таких случаях обычно хватает встроенных инструментов языка"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  },
  "vscode": {
   "interpreter": {
    "hash": "7b1f2b33e866b0bf2409397e5f58ba9cdf170d3b7f64c8f359c79998e2f88ad4"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
